resume_tailor_task:
  description: >
   			You are a very competent resume analyzer that generates resumes tailored to specific job profiles.

            You have been provided with a job description and a resume. Your job is to generate a tailored resume for the user.
            Job description: {job_description}
            Resume text: {resume_text}
            
            Extract the following from the job description.
            Job Responsibilities: Outline the primary tasks and expectations for the role.This can be specified in different ways like "What you will do, Your daily tasks, Your responsibilities, Your duties etc. or something similarly worded"
            Job Qualifications: Highlight the required skills, experience, and knowledge.

            Tailor following sections of the original resume while keeping the other sections intact
            please tailor that too.

            Skills Section:
            Retain the original formatting and structure of the resume's skills section.
            Add keywords and skills mentioned in the job description that are critical for the role.
            Ensure the length of this section remains consistent with the original resume.

            Summary Section:
            Rewrite the summary to highlight relevant experiences and skills from the resume that align with the job responsibilities and qualifications.
            Use industry buzzwords and metrics where applicable, keeping the tone professional and concise.

            Professional Experience Section:
            - Enhance each job entry by rewording and restructuring responsibilities to emphasize alignment with the job responsibilities and job qualifications.
            - Integrate key performance indicators (KPIs), metrics, and achievements directly relevant to the role.
            - Focus on areas of overlap between the candidate's resume and the job description.
            - Do not add or infer skills, experiences, or achievements that are not explicitly stated.
            - Use the language, tone, and keywords from the job description wherever they authentically match.
            - Do not exaggerate the scope, scale, or impact of the candidate's accomplishments.
            - Count and maintain the same number of experiences as in the original resume.

            """
  expected_output: >
    Generate a full resume for the user. The tailored resume would have all sections from the original resume
  agent: resume_generator

resume_review_task:
  description: >
    You are a seasoned resume reviewer with a keen eye for detail. Your job is to review the resume generated by the resume generator and provide feedback. 
    You need to pay attention to the following:
    - Creatively reword the resume and highlight experiences that are referred in the job description
    - Make sure to not mix up the experiences in different companies.
    - Replace the words with more appropriate ones if needed.
    - Keep the length of the resume same as original resume.
    - The generated resume should be ATS friendly.
  expected_output: >
    -Provide an ATS match score for before and after tailoring of the resume
    -A list of recommendations on how to further improve the tailored resume (if needed)
  agent: resume_reviewer
 
  
 
final_resume_generator_task:
  description: >
    You are a final resume generator that uses the feedback from the resume reviewer to improve the tailored resume 
    generated by the resume generator. 
    - Read the job description
    - Go through each job experience and apply the feedback from resume_reviewer agent to improve the resume
    -
    - Make sure to not fake any information or fabricate metrics. Tailored resume should be a true representation of the user's work experience
    Job description: {job_description}
    Original Resume text: {resume_text}
  expected_output: >
    Generate the output as a pydantic object of type TailoredResume with the following property fields. return a clean json output without any prefix or suffix.
    "Before": #calculate ATS matching score between orginal resume and the job profile
    "After": #calculate ATS matching score between tailored resume and the job profile
    "Changes": #List of all changes made to the original resume. This would be a text field with list of changes separated by commas
    "TailoredResume": #tailored resume in the same markdown format as the original resume. The only update should be the content of the resume
  agent: final_resume_generator
  context: [resume_review_task] 
